services:
  agent:
    image: datadog/agent:7
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    cgroup: host
    environment:
      DD_LOG_LEVEL: debug
      DD_ENV: docker-keisuke-mac
      DD_APM_ENABLED: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_API_KEY: ${DD_API_KEY}
      DD_LOGS_ENABLED: true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    environment:
      JAVA_OPTS: >-
        -javaagent:/opt/dd-java-agent.jar
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.port=9012
        -Dcom.sun.management.jmxremote.rmi.port=9012
        -Dtomcat.util.buf.StringCache.byte.enabled=true
        -Dtomcat.util.buf.StringCache.char.enabled=true
        -Dtomcat.util.buf.StringCache.trainThreshold=100
        -Ddd.trace.client-ip.enabled=true
      DD_ENV: docker-keisuke-mac
      DD_SERVICE: keisuke-tomcat
      DD_AGENT_HOST: agent
      DD_TRACE_DEBUG: true
      DD_TRACE_STARTUP_LOGS: false
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  client:
    image: curlimages/curl:latest
    command: sh -c "while true; do curl -v http://nginx:80/index.html; sleep 10; done"
